### PR TITLE
Add contributing info and update README.md

### LINKED ISSUE #2: Add a contributing guide and update the README
I plan to use most of the contributing guide from the Hyperloop team that I made recently.

I will add the style for Python, which will be PEP8 with NumPy docstrings. We can choose a linter later.

- [x] Contributing guide.
- [x] Style specifications.
- [x] Update the README to link appropriate docs.

### PR DESCRIPTION
**Pull request by stegnerw**
Contributing info is added and the README is updated accordingly.

Closes #2

### CODE REVIEW

**Comment by stegnerw** [comment]
Please make sure you agree with everything in the contributing guide. I am open to discussion of changes.

**Review by Siddharth-Barve — COMMENTED** [review]
looks good

**Review by liu2g — APPROVED** [review]
Looks good to me

**Review by Siddharth-Barve — APPROVED** [review]
looks good

**Pull request merged**
